plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.google.services)
    alias(libs.plugins.compose.compiler)
}

android {
    namespace 'com.example.sothuchi'
    compileSdk 34

    defaultConfig {
        applicationId "com.example.sothuchi"
        minSdk 30
        targetSdk 34
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
    buildFeatures {
        dataBinding true
        viewBinding true
        compose true
    }
}

dependencies {
    implementation platform(libs.compose.bom)
    implementation libs.compose.ui
    implementation libs.compose.material3
    implementation libs.compose.ui.tooling.preview
    debugImplementation libs.compose.ui.tooling
    
    implementation platform('com.google.firebase:firebase-bom:34.11.0')
    implementation 'com.google.firebase:firebase-analytics'
    implementation 'com.google.firebase:firebase-auth'
    implementation 'com.google.firebase:firebase-storage'
    implementation 'com.google.firebase:firebase-database'
    implementation 'com.google.firebase:firebase-firestore'
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
    
    implementation libs.appcompat
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout
    implementation libs.lifecycle.livedata.ktx
    implementation libs.lifecycle.viewmodel.ktx
    implementation libs.mpandroidchart
    
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    // server local ngrok
    implementation("com.squareup.okhttp3:okhttp:4.12.0")


    // Excel generation
    implementation 'org.apache.poi:poi-ooxml:5.2.3'
}
